import type { Metadata } from "next";
import { Catamaran, Castoro_Titling, Carattere } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import HeroPage from "./hero/page";

const catamaran = Catamaran({
  variable: "--font-catamaran",
  subsets: ["latin"],
});

const castoroTitling = Castoro_Titling({
  variable: "--font-castoro-titling",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const carattere = Carattere({
  variable: "--font-carattere",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${catamaran.variable} ${castoroTitling.variable} ${carattere.variable} antialiased`}
      >
        <HeroPage />
        {children}
        <Footer />
      </body>
    </html>
  );
}
